### ISSUE TITLE
Gather initial requirements from shareholders

### ISSUE THREAD

**Issue by lemeow125** [lemeow125/EquipmentTracker-Backend#4]
*Assignees*
- Angelica Panchito
- Kim Arandid

**Sub-tasks**
- [x] Decide on preferred development methodology
- [x] Decide on scope of the project
- [x] List down essential features
- [x] Evaluate security features needed
- [x] List down user roles and permissions required
- [x] Decide on tech stack (for backend & for frontend)
- [x] List down system and network requirements (for backend & for frontend)

**Comment by lemeow125** [comment]
**Development Methodology**
Agile Methodology

**Essential Features**

- Login & Registration (with email activation)
- Individual item status tracking (items can be defective, functional, missing, or out for repair/maintenance
